# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano//zmk" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9//zmk
#   - board: nice_nano//zmk
#     shield: reviung41
#
---
include:
  - board: nice_nano//zmk
    shield: tako_left
    artifact-name: tako_left_ec

  - board: nice_nano//zmk
    shield: tako_left
    snippet: enable_ec_calibrator
    cmake-args: -DZMK_EXTRA_MODULES="${GITHUB_WORKSPACE}/config/tako_ec_autosave"
    artifact-name: tako_left_ec_calibrator_autosave

  - board: nice_nano//zmk
    shield: tako_left
    snippet: enable_ec_calibrator
    cmake-args: -DZMK_EXTRA_MODULES="${GITHUB_WORKSPACE}/config/tako_ec_autosave" -DCONFIG_ZMK_KSCAN_EC_MATRIX_SETTINGS_INIT_LOAD=n
    artifact-name: tako_left_ec_calibrator_autosave_no_load
