CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

# IDLE. Slowing down matrix scan rate to save power.
CONFIG_ZMK_IDLE_TIMEOUT=5000

# Deep sleep.
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

# Persistent calibration storage.
CONFIG_SETTINGS=y
CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y

# Pete Johanson EC matrix support.
CONFIG_ZMK_KSCAN_EC_MATRIX_SETTINGS=y
CONFIG_ZMK_KSCAN_EC_MATRIX_FAKE_OPEN_DRAIN=y
CONFIG_ZMK_KSCAN_EC_MATRIX_DYNAMIC_POLL_RATE=y
